export { useProducts } from "../redux/ducks/product/index"
export { useItems } from "../redux/ducks/cart/index"
export { usePlayers } from "../redux/ducks/athletes/index"
export { useFeatPlayers } from "../redux/ducks/featuredAth/index"
export { useFeatProducts } from "../redux/ducks/featuredProd/index"
